package.json
src/App.tsx
src/index.css
src/main.tsx
src/pages/Intro.tsx
src/pages/Login.tsx
src/pages/Main.tsx
src/pages/SignUp.tsx
tailwind.config.cjs

[feat] login pages added

---

src/main.tsx
src/pages/Intro.tsx
src/pages/Login.tsx
src/pages/Main.tsx
src/pages/SignUp.tsx

[feat] now user and login to the main page

---

package-lock.json
package.json
src/organism/Chat.tsx
src/organism/Directmsg.tsx
src/organism/Friends.tsx
src/organism/Nav.tsx
src/pages/Temp.tsx

Temp chat slide

---

src/organism/Chat.tsx
src/organism/ChatingRoom.tsx
src/organism/Directmsg.tsx

[temp] chat socket

---

src/mocks/friend.ts
src/mocks/login.ts
src/mocks/worker.ts
src/pages/Intro.tsx
src/pages/Login.tsx
src/pages/SignUp.tsx
src/states/user/signUp.ts

- Intro, Login 페이지 리펙토링
- 로그인 -> 회원가입 이동 시 필요한 데이터를 recoil을 통해 전달

Refactor login flow

---

src/organism/ChatingRoom.tsx

solve textarea feat

---

src/atom/Button.tsx
src/atom/GameMatchedUserInfo.tsx
src/molecule/Game.tsx
src/molecule/GameMatched.tsx
src/pages/SignUp.tsx

게임 매치 화면에서
- 각 플레이어의 프로필 이미지
- 상대플레이어의 레디 여부
- 플레이어가 선택한 난이도
를 확인할 수 있도록 수정하였습니다.
이를 위해 Button 컴포넌트를 살짝 수정하여 
focus시 표시되던 테두리가 hover시 표시되도록 변경하였습니다.

[feat] when players can check current difficulty and theme on GameMatched

---

src/molecule/CurrentUserWidget.tsx
src/organism/FriendsList.tsx
src/organism/Nav.tsx
src/organism/SearchUserProfileForm.tsx
src/organism/UserProfileModal.tsx
src/pages/Main.tsx
src/states/user/profileUser.ts

Feat user profile

---

src/organism/Chat.tsx
src/organism/ChatingRoom.tsx
src/states/roomInfoState.ts

resolve Roominfo convert into Recoil

---

src/organism/ChatingRoom.tsx

Fix chat message type

---

src/hooks/chat.ts
src/molecule/SideBarHeader.tsx
src/molecule/StatusIndicator.tsx
src/organism/Chat.tsx
src/organism/ChatingRoom.tsx
src/organism/Directmsg.tsx
src/organism/DirectmsgRoom.tsx
src/organism/Friends.tsx
src/organism/FriendsList.tsx
src/states/currentDMOpponent.ts

[WIP] Feat dm

---

src/molecule/Game.tsx
src/molecule/GameIntro.tsx
src/molecule/GameOnMatching.tsx
src/molecule/GamePlayerInfoBar.tsx
src/organism/FriendsList.tsx
src/pages/Main.tsx
src/templates/GameContainer.tsx
tsconfig.json

54 feat normal match

---

src/hooks/notification.tsx
src/molecule/NotificationChat.tsx
src/molecule/NotificationGame.tsx

- 소켓을 통해 받을 데이터 타입 수정
- 이미 상대방과 dm중이라면 알림이 오지 않도록 수정

Fix notification data type

---

src/hooks/matchHistory.ts
src/hooks/profileModal.ts
src/organism/UserMatchHistory.tsx
src/organism/UserProfileModal.tsx

Feat match history

---

src/App.tsx
src/pages/NotFound.tsx

[feat] 404 page added

---

src/organism/DirectmsgList.tsx
src/organism/DirectmsgRoom.tsx

- dm 인터페이스에 프로필 보기, 게임 초대, 차단이 가능하도록 추가

Feat dm extra interface

---

src/hooks/game.ts
src/organism/ChatingRoom.tsx
src/organism/CreateChatForm.tsx
src/organism/DirectmsgList.tsx
src/organism/DirectmsgRoom.tsx
src/organism/RequestedFriendsList.tsx

Fix fetcher

---

src/organism/FriendsList.tsx

Prevent profile image shrinking

---

src/hooks/chat.ts
src/molecule/CurrentUserWidget.tsx
src/molecule/SideBarHeader.tsx
src/organism/Chat.tsx
src/organism/DirectmsgList.tsx
src/organism/FriendsList.tsx

- 사이드바의 패딩을 일정하게 수정
- 채팅 리스트에서 채팅방의 타입을 보여주도록 수정
- 모든 채팅 리스트에서 이미 참가한 채팅방은 필터링해서 보여주도록 수정

Fix style and chat list

---

src/index.css

Chage scrollbar style

---

src/organism/AddFriendForm.tsx

Add notificaiton for add friend request

---

src/organism/ChatingRoom.tsx

fix chat room icon

---

src/hooks/chat.ts
src/organism/Chat.tsx

Feat password form to enter chat

---

src/hooks/friends.ts
src/hooks/notification.tsx
src/molecule/NotificationUser.tsx
src/organism/RequestedFriendsList.tsx

Feat user notification

---

src/atom/Button.tsx
src/organism/Chat.tsx
src/organism/DirectmsgList.tsx
src/organism/Nav.tsx
src/organism/RequestedFriendsList.tsx

- 파이어폭스의 flex 속성의 기본 정렬 방향이 크롬과 달라 방향을 명시적으로 나타냄
- 자잘한 패딩 수정

Fix align and padding

---

src/App.tsx
src/hooks/chat.ts
src/organism/ChatingRoom.tsx
src/organism/CreateChatForm.tsx

Feat chatting room setting menu

---

src/hooks/notification.tsx
src/molecule/NotificationGame.tsx
src/templates/GameContainer.tsx

- 게임 중 초대 알림을 받을 수 없도록 수정하였습니다.

[fix] now user can't get invitation toast while playing game

---

src/molecule/Game.tsx

- 게임 중 불필요하게 리렌더링 되는 부분을 발견하여 해당 부분 수정하였습니다.
- 그동안 뚝뚝 끊겼던 게임은 아마 이것 때문일수도...;

[fix] unnecessary re-redering during gaming fixed

---

src/hooks/user.ts
src/organism/EditAccountInfoModal.tsx
src/pages/SignUp.tsx

- 닉네임 규칙이 추가되었습니다
- 2자 이상 16자 이하
- 닉네임에 특수문자가 들어갈 시 닉네임으로 유저 api 조회가 안되는 이슈가 있어 아예 닉네임에 특수문자 들어가는것 다 막았습니다.

[fix] nickname rule added

---

src/organism/ChatingRoom.tsx

add view profile

---

src/hooks/mutation/user.ts
src/pages/Login.tsx

- 회원가입시 2fa 페이지로 이동해버리는 문제
- 닉네임 중복시 에러 핸들링 문제

Fix sign up

---

src/hooks/mutation/chat.ts
src/organism/ChatingRoom.tsx

Fix some error for chat

---

src/hooks/mutation/user.ts

- generate 버튼이 제대로 동작하지 않는 것을 수정하였습니다.

[fix] 2fa generation logic fixed

---

src/molecule/GamePlayerInfoBar.tsx

- GamePlayerInfoBar 에서 유저의 프로필 이미지 크기를 고정하였습니다.

[fix] game play info user profile image css fixed

---

src/hooks/mutation/chat.ts
src/organism/EditRoomInfoForm.tsx

- protected <-> any type 간의 변경은 password 수정으로, 단 private -> protected는 불가능하다.
- public <-> private 간의 변경은 access 수정으로

Fix access type change

---

src/hooks/chat.ts
src/hooks/mutation/user.ts
src/hooks/notification.tsx
src/hooks/query/chat.ts
src/hooks/query/dm.ts
src/hooks/query/user.ts
src/organism/ChatingRoom.tsx

Fix some bugs

---

src/organism/ShowUserList.tsx

user chat role justify set

---

src/templates/GameContainer.tsx

[fix] game socket dependency fixed

---

src/hooks/mutation/user.ts
src/hooks/query/user.ts
src/molecule/CurrentUserWidget.tsx
src/molecule/OptionMenu.tsx
src/organism/BlockedFriendsList.tsx
src/organism/DirectmsgRoom.tsx
src/organism/Friends.tsx
src/organism/FriendsList.tsx
src/organism/RequestedFriendsList.tsx
src/organism/ShowUserList.tsx

Add block list

---

src/pages/Intro.tsx

서버 응답에 담긴 provider 값을 이용해 provider 객체를 직접 참조하고 있어 서버와 동일한 키 값으로 수정하였습니다.

Fix provider key value

---

src/hooks/user.ts

- 닉네임에 한글, 영어, _ 만 쓸 수 있도록 규칙을 바꿨습니다.

[fix] username rule fixed

---

src/templates/GameContainer.tsx

- 게임 소켓의 api url을 env에서 받아오도록 변경하였습니다.

[fix] game socket url is now get from env

---

Dockerfile
package-lock.json
package.json

- 배포 과정을 도커 이미지로 작성합니다
- 환경변수 설정과 최종 테스트가 마저 필요합니다

[chore] deploy with docker
